### ISSUE TITLE
Error when use rawhic input

### ISSUE THREAD

**Issue by EddieLv** [wangjk321/HiC1Dmetrics#2]
My command is:
h1d one CI {sample}.cis10kb.hic ${res_h1d} chr19
-p {sample}_CI --datatype rawhic --msi fithic2 --gt {ppn}
The error message is:
Start dump matrix from hic file
Could not read hic file: Index 0 out of bounds for length 0
rm: cannot delete 'pluscol.chr194c9fa7d7.temp': no such file or directory
rm: cannot delete '././MatrixTemp0.5919967965865072/50000/observed.KR.chr19.txt': no such file or directory
Finish dump
Calculating 1D metrics for one sample
File does not exist, please check your file path

My .hic file is create through juicer_tools pre without normalization.

**Comment by EddieLv** [comment]
I cannot find the parameter to attach the version of my juicer tools.
And meanwhile, I found the error is caused by makeMatrixIntra.sh, it did look like the error of juicer dump.

**Comment by wangjk321** [comment]
Thank you for your feadback. The reason of this bug is:
` .hic` file made by newer `Juicer pre` is incompatible with older `Juicer_tools dump`.

I will update the code soon to support customized `juicer_tools`. BTW, current version in makeMatrixIntra.sh is` Juicer_tools v1.11.04`

**Comment by wangjk321** [comment]
If you know how to modify the python code, Just modify line 25 in `makeMatrixIntra.sh` 
from
`juicertool="java -Xms512m -Xmx20480m -jar $juicer"
`
to
`juicertool="java -Xms512m -Xmx20480m -jar $your_correct_version_of_juicertools"`

**Comment by EddieLv** [comment]
Thanks for your reply! The bug is solved!
