### ISSUE TITLE
plot TAD 

### ISSUE THREAD

**Issue by Zheng19w** [wangjk321/HiC1Dmetrics#3]
![image](https://github.com/wangjk321/HiC1Dmetrics/assets/106860091/db5558ca-fbe4-4695-ad5e-cae0dc3f48ed)
Dear Professor: Hello, I have two questions

① I want to draw a similar picture, but I can't find the code in the reference documentation

② Why does the matrix I drew have a row of white squares under the ground

Looking forward to your reply!
h1d one CI ./dabai.hic \
    50000 1 -p 300000 -o dabai_CI_chr1 --datatype rawhic \
    --gt ./scrofa.fa.sizes --draw -s 26000000 -e 33000000

get observed.KR.chr1.matrix.gz

h1d one CI ./observed.KR.chr1.matrix.gz \
    50000 1 -p 300000 -o Control_CI_chr21 --datatype matrix \
  --draw -s 26000000 -e 33000000

![image](https://github.com/wangjk321/HiC1Dmetrics/assets/106860091/cd1e23b8-a906-41b5-9d7f-b407546d2078)

**Comment by wangjk321** [comment]
1. where did you find the figure. I need the source then I can find the code.

2. Because your contact matrix indeed have some zeros, maybe due to read depth, etc. Please check other regions or increase the resolution (e.g., 100000).

**Comment by Zheng19w** [comment]
![image](https://github.com/wangjk321/HiC1Dmetrics/assets/106860091/6f03fa56-e7cf-4c61-8a81-7ecfe3beef24)

**Comment by wangjk321** [comment]
You can try `--plottype tad`

the code is something like:

```
h1d basic plot ./test_data/GSE104334_Ctrl.chr21.matrix.gz \
	50000 chr21 --datatype matrix -o testplot --plottype tad \
	-s 27500000 -e 32500000
```

**Comment by Zheng19w** [comment]
Hello, do I have my own TAD file to import? Use my own tad file

**Comment by wangjk321** [comment]
Because TAD file have many format, we cannot support customized TAD. Instead, you can modify this line 

https://github.com/wangjk321/HiC1Dmetrics/blob/013d11ed8080b78175f9d913d1094c54512d4def/h1d/callDirectionalTAD.py#L9C83-L9C83

for example, 

`Tad = pd.read_csv("TADfile.tsv")`

this is the format requirement for TAD file

```
Tad["chr"] = chrlist
Tad["TADstart"] = TADstart
Tad["TADend"] = TADend
```

**Comment by Zheng19w** [comment]
TADfile.tsv 文件如下：
1       1050000 1500000
1       1500000 1625000
1       1625000 1950000
1       1950000 2275000
1       2275000 2650000
1       2650000 2925000
1       2925000 3425000
1       3425000 3625000
1       3625000 4250000
1       4250000 4725000
1       4725000 4875000
1       4875000 5125000
1       5125000 5700000
1       5700000 6250000
1       6250000 6700000
1       6700000 7075000
1       7075000 7375000
1       7375000 7700000
1       7700000 8125000
1       8125000 8250000
1       8250000 8625000
1       8625000 9025000
1       9025000 9150000
1       9150000 9350000
1       9350000 9700000
1       9700000 9950000
您好，我需要添加标题吗 chrlist  TADstart  TADend  这个文件是制表符分开的

**Comment by Zheng19w** [comment]
Traceback (most recent call last):
  File "/work/home/xiang1996/miniconda3/envs/coolbox/bin/h1d", line 8, in <module>
    sys.exit(CLI())
  File "/work/home/xiang1996/miniconda3/envs/coolbox/lib/python3.10/site-packages/h1d/__main__.py", line 402, in CLI
    func(args)
  File "/work/home/xiang1996/miniconda3/envs/coolbox/lib/python3.10/site-packages/h1d/__main__.py", line 46, in func_basic
    PlotTAD(path,args.resolution,args.chromosome,startSite=args.start,endSite=args.end).drawTAD(squareSize=int(args.parameter))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by wangjk321** [comment]
I will update next version to support the customized TAD file.

**Comment by Zheng19w** [comment]
谢谢您的回复，感谢您开发了这个非常棒的工具



---- Replied Message ----
| From | Jiankang ***@***.***> |
| Date | 06/25/2023 21:33 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [wangjk321/HiC1Dmetrics] plot TAD (Issue #3) |

I will update next version to support the customized TAD file.

**Comment by Zheng19w** [comment]
如何可以加载一些bw文件，用于表观多组学数据展示那就太棒了



---- Replied Message ----
| From | Jiankang ***@***.***> |
| Date | 06/25/2023 21:33 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [wangjk321/HiC1Dmetrics] plot TAD (Issue #3) |

I will update next version to support the customized TAD file.
