### ISSUE TITLE
Hi ! Does "raw .hic defined by juicer software." mean 'inter.hic' or 'inter_30.hic' output by the juicer?

### ISSUE THREAD

**Issue by kuangzhuoran** [wangjk321/HiC1Dmetrics#4]
Does "raw .hic defined by juicer software." mean 'inter.hic' or 'inter_30.hic' output by the juicer?

**Comment by wangjk321** [comment]
Hi, thank you for your interest. Yes, it is by juicer. We recommend to use 'inter_30.hic' .

**Comment by kuangzhuoran** [comment]
Thank you
