### ISSUE TITLE
Errow when used rawhic input: "File does not exist, please check your file path"

### ISSUE THREAD

**Issue by kuangzhuoran** [wangjk321/HiC1Dmetrics#5]
Hi !

My command is:
h1d call TAD  ./carmeli.30.hic  25000  Chr29  -o test  --datatype rawhic  --gt ./carmeli.length

The error message is:
Start dump matrix from hic file
Finish dump
File does not exist, please check your file path

I saw a similar error at "https://github.com/wangjk321/HiC1Dmetrics/issues/2", but I found a folder called ‘MatrixTemp0.05099345739986205’ created after running the command line.
It generates the file "observed.KR.chrChr29.matrix.gz",  which means "Juicer_tools dump" is working.

When I calculated the PC1 value, my command is "h1d one PC1 ./carmeli.30.hic 50000 Chr29 -o test --datatype rawhic --gt ./carmeli.length -p ./carmeli.geneDensity.txt"
I encountered a similar error report:
Start dump matrix from hic file
Finish dump
Calculating 1D metrics for one sample
File does not exist, please check your file path

My h1d version is 0.1.29; 
My Linux system is CentOS Stream release 8

**Comment by kuangzhuoran** [comment]
As for "--gt ./carmeli.length"

The path to this file is correct, I've also tried absolute paths still not working.

**Comment by wangjk321** [comment]
Please refer to this issue https://github.com/wangjk321/HiC1Dmetrics/issues/1. I think the problem is your chromosome name is "Chr29" not "chr29"

**Comment by kuangzhuoran** [comment]
Well, I'm trying to use the "MatrixTemp0.05099345739986205/observed.KR.chrChr29.matrix.gz" that I just generated as an input file. It works.
And my command is "h1d call TAD ./MatrixTemp0.9770529357100954/25000/observed.KR.chrChr29.matrix.gz 25000 Chr29 -o test --gt ./carmeli.length"

It seems that I need to convert the .hic file output by juicer to “matrix” format before continuing to run the other analyses。

**Comment by wangjk321** [comment]
> Please refer to this issue #1. I think the problem is your chromosome name is "Chr29" not "chr29"

Please check this. That's why the output name is strange, like "chrChr29"

**Comment by kuangzhuoran** [comment]
Yes, It is "Chr29" not "chr29".
I know how to handle it.

Thank you !

**Comment by Simple53** [comment]
Hi，I have a similar problem when using `h1d two`.  The name of the dumped hic matrix looks good. But I know my matrix chromosomes do not have a 'chr' prefix, is it could be the reson? How to solve it? Thanks.
```
├── MatrixTemp0.4904302265940076
│   └── 50000
│       └── observed.KR.chr21.matrix.gz
├── MatrixTemp0.6677646599167062
│   └── 50000
│       └── observed.KR.chr21.matrix.gz
```
