### ISSUE TITLE
How should I set the parameters to obtain all chromosome TADs

### ISSUE THREAD

**Issue by v587dexinxin** [wangjk321/HiC1Dmetrics#7]
Hello author, I would like to obtain stripTAD information for all chromosomes at once. However, it seems that your software only provides calculations for individual chromosomes at a time. Could you please advise on how to set the parameters to obtain TAD information for all chromosome numbers in one go?

**Comment by wangjk321** [comment]
Hi, it is not supported at the moment. However, you can easily write a loop to execute all chromosomes.
